export const countryMap: Record<string, { flag: string; name: string }> = {
    US: { flag: '/flag/us.png', name: 'USA' },
    IN: { flag: '/flag/in.png', name: 'India' },
    GB: { flag: '/flag/gb.png', name: 'United Kingdom' },
    CA: { flag: '/flag/ca.png', name: 'Canada' },
    AU: { flag: '/flag/au.png', name: 'Australia' },
    DE: { flag: '/flag/de.png', name: 'Germany' },
    FR: { flag: '/flag/fr.png', name: 'France' },
    JP: { flag: '/flag/jp.png', name: 'Japan' },
    CN: { flag: '/flag/cn.png', name: 'China' },
    BR: { flag: '/flag/br.png', name: 'Brazil' },
    RU: { flag: '/flag/ru.png', name: 'Russia' },
    ZA: { flag: '/flag/za.png', name: 'South Africa' },
    IT: { flag: '/flag/it.png', name: 'Italy' },
    ES: { flag: '/flag/es.png', name: 'Spain' },
    MX: { flag: '/flag/mx.png', name: 'Mexico' },
    ID: { flag: '/flag/id.png', name: 'Indonesia' },
    KR: { flag: '/flag/kr.png', name: 'South Korea' },
    NL: { flag: '/flag/nl.png', name: 'Netherlands' },
    SA: { flag: '/flag/sa.png', name: 'Saudi Arabia' },
    SE: { flag: '/flag/se.png', name: 'Sweden' },
    CH: { flag: '/flag/ch.png', name: 'Switzerland' },
    AE: { flag: '/flag/ae.png', name: 'UAE' },
    SG: { flag: '/flag/sg.png', name: 'Singapore' },
    AR: { flag: '/flag/ar.png', name: 'Argentina' },
    NG: { flag: '/flag/ng.png', name: 'Nigeria' },
    EG: { flag: '/flag/eg.png', name: 'Egypt' },
    TH: { flag: '/flag/th.png', name: 'Thailand' },
    VN: { flag: '/flag/vn.png', name: 'Vietnam' },
    PK: { flag: '/flag/pk.png', name: 'Pakistan' },
    BD: { flag: '/flag/bd.png', name: 'Bangladesh' },
    TR: { flag: '/flag/tr.png', name: 'Turkey' },
    PL: { flag: '/flag/pl.png', name: 'Poland' },
    IR: { flag: '/flag/ir.png', name: 'Iran' },
    MY: { flag: '/flag/my.png', name: 'Malaysia' },
    PH: { flag: '/flag/ph.png', name: 'Philippines' },
    UA: { flag: '/flag/ua.png', name: 'Ukraine' },
    BE: { flag: '/flag/be.png', name: 'Belgium' },
    IL: { flag: '/flag/il.png', name: 'Israel' },
    AT: { flag: '/flag/at.png', name: 'Austria' },
    NO: { flag: '/flag/no.png', name: 'Norway' },
    DK: { flag: '/flag/dk.png', name: 'Denmark' },
    FI: { flag: '/flag/fi.png', name: 'Finland' },
    IE: { flag: '/flag/ie.png', name: 'Ireland' },
    NZ: { flag: '/flag/nz.png', name: 'New Zealand' },
    PT: { flag: '/flag/pt.png', name: 'Portugal' },
    GR: { flag: '/flag/gr.png', name: 'Greece' },
    CZ: { flag: '/flag/cz.png', name: 'Czech Republic' },
    HU: { flag: '/flag/hu.png', name: 'Hungary' },
    RO: { flag: '/flag/ro.png', name: 'Romania' },
    CL: { flag: '/flag/cl.png', name: 'Chile' },
    CO: { flag: '/flag/co.png', name: 'Colombia' },
    PE: { flag: '/flag/pe.png', name: 'Peru' },
    VE: { flag: '/flag/ve.png', name: 'Venezuela' },
    QA: { flag: '/flag/qa.png', name: 'Qatar' },
    KW: { flag: '/flag/kw.png', name: 'Kuwait' },
    KE: { flag: '/flag/ke.png', name: 'Kenya' },
    GH: { flag: '/flag/gh.png', name: 'Ghana' },
    MA: { flag: '/flag/ma.png', name: 'Morocco' },
    DZ: { flag: '/flag/dz.png', name: 'Algeria' },
    ET: { flag: '/flag/et.png', name: 'Ethiopia' },
    LK: { flag: '/flag/lk.png', name: 'Sri Lanka' },
    MM: { flag: '/flag/mm.png', name: 'Myanmar' },
    NP: { flag: '/flag/np.png', name: 'Nepal' },
    AF: { flag: '/flag/af.png', name: 'Afghanistan' },
    UZ: { flag: '/flag/uz.png', name: 'Uzbekistan' },
    KZ: { flag: '/flag/kz.png', name: 'Kazakhstan' },
    BY: { flag: '/flag/by.png', name: 'Belarus' },
    RS: { flag: '/flag/rs.png', name: 'Serbia' },
    HR: { flag: '/flag/hr.png', name: 'Croatia' },
    BG: { flag: '/flag/bg.png', name: 'Bulgaria' },
    SK: { flag: '/flag/sk.png', name: 'Slovakia' },
    SI: { flag: '/flag/si.png', name: 'Slovenia' },
    LT: { flag: '/flag/lt.png', name: 'Lithuania' },
    LV: { flag: '/flag/lv.png', name: 'Latvia' },
    EE: { flag: '/flag/ee.png', name: 'Estonia' },
    IS: { flag: '/flag/is.png', name: 'Iceland' },
    LU: { flag: '/flag/lu.png', name: 'Luxembourg' },
    MT: { flag: '/flag/mt.png', name: 'Malta' },
    CY: { flag: '/flag/cy.png', name: 'Cyprus' },
    TW: { flag: '/flag/tw.png', name: 'Taiwan' },
    HK: { flag: '/flag/hk.png', name: 'Hong Kong' },
    MO: { flag: '/flag/mo.png', name: 'Macau' },
    JO: { flag: '/flag/jo.png', name: 'Jordan' },
    LB: { flag: '/flag/lb.png', name: 'Lebanon' },
    OM: { flag: '/flag/om.png', name: 'Oman' },
    BH: { flag: '/flag/bh.png', name: 'Bahrain' },
    TN: { flag: '/flag/tn.png', name: 'Tunisia' },
    UY: { flag: '/flag/uy.png', name: 'Uruguay' },
    EC: { flag: '/flag/ec.png', name: 'Ecuador' },
    BO: { flag: '/flag/bo.png', name: 'Bolivia' },
    PY: { flag: '/flag/py.png', name: 'Paraguay' },
    CR: { flag: '/flag/cr.png', name: 'Costa Rica' },
    PA: { flag: '/flag/pa.png', name: 'Panama' },
    DO: { flag: '/flag/do.png', name: 'Dominican Republic' },
    CU: { flag: '/flag/cu.png', name: 'Cuba' },
    JM: { flag: '/flag/jm.png', name: 'Jamaica' },
    HT: { flag: '/flag/ht.png', name: 'Haiti' },
    BS: { flag: '/flag/bs.png', name: 'Bahamas' },
    BB: { flag: '/flag/bb.png', name: 'Barbados' },
    TT: { flag: '/flag/tt.png', name: 'Trinidad and Tobago' },
    GY: { flag: '/flag/gy.png', name: 'Guyana' },
    SR: { flag: '/flag/sr.png', name: 'Suriname' },
    PG: { flag: '/flag/pg.png', name: 'Papua New Guinea' },
    FJ: { flag: '/flag/fj.png', name: 'Fiji' },
    SB: { flag: '/flag/sb.png', name: 'Solomon Islands' },
    VU: { flag: '/flag/vu.png', name: 'Vanuatu' },
    NC: { flag: '/flag/nc.png', name: 'New Caledonia' },
    PF: { flag: '/flag/pf.png', name: 'French Polynesia' },
    ZM: { flag: '/flag/zm.png', name: 'Zambia' },
    ZW: { flag: '/flag/zw.png', name: 'Zimbabwe' },
    AO: { flag: '/flag/ao.png', name: 'Angola' },
    MZ: { flag: '/flag/mz.png', name: 'Mozambique' },
    BW: { flag: '/flag/bw.png', name: 'Botswana' },
    NA: { flag: '/flag/na.png', name: 'Namibia' },
    SN: { flag: '/flag/sn.png', name: 'Senegal' },
    CI: { flag: '/flag/ci.png', name: 'Ivory Coast' },
    CM: { flag: '/flag/cm.png', name: 'Cameroon' },
    UG: { flag: '/flag/ug.png', name: 'Uganda' },
    TZ: { flag: '/flag/tz.png', name: 'Tanzania' },
    RW: { flag: '/flag/rw.png', name: 'Rwanda' },
    SD: { flag: '/flag/sd.png', name: 'Sudan' },
    SS: { flag: '/flag/ss.png', name: 'South Sudan' },
    LY: { flag: '/flag/ly.png', name: 'Libya' },
    IQ: { flag: '/flag/iq.png', name: 'Iraq' },
    YE: { flag: '/flag/ye.png', name: 'Yemen' },
    SY: { flag: '/flag/sy.png', name: 'Syria' },
    AM: { flag: '/flag/am.png', name: 'Armenia' },
    AZ: { flag: '/flag/az.png', name: 'Azerbaijan' },
    GE: { flag: '/flag/ge.png', name: 'Georgia' },
    MD: { flag: '/flag/md.png', name: 'Moldova' },
    BA: { flag: '/flag/ba.png', name: 'Bosnia' },
    AL: { flag: '/flag/al.png', name: 'Albania' },
    MK: { flag: '/flag/mk.png', name: 'North Macedonia' },
    ME: { flag: '/flag/me.png', name: 'Montenegro' },
    XK: { flag: '/flag/xk.png', name: 'Kosovo' },
};
